#pragma once

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstddef>
#include <list>
#include <memory>
#include <mutex>

#include "glog/logging.h"
#include "util/Debug.h"
#include "util/Likely.h"
#include "util/PerformanceReporter.h"
#include "util/TimeConv.h"
using namespace std::chrono_literals;

namespace bench
{
class TokenWrap;
class TokenCore
{
public:
    TokenCore(int64_t task_nr);
    // does not allow copy nor move
    // because @TokenWrap owns a pointer to @this.
    TokenCore(const TokenCore &) = delete;
    TokenCore &operator=(TokenCore &) = delete;
    TokenCore(TokenCore &&) = delete;
    TokenCore &operator=(TokenCore &&) = delete;

    TokenWrap token_wrap(size_t batch_nr, ssize_t per_sync_at_least_nr);

    void reset(int64_t task_nr);

    const std::atomic<int64_t> &inner() const;
    std::atomic<int64_t> &inner();

private:
    std::atomic<int64_t> remain_{};
    int64_t task_nr_{};
};

class TokenWrap
{
public:
    TokenWrap(TokenCore &core,
              int64_t task_nr,
              size_t batch_nr,
              ssize_t min_batch_size);
    /**
     * @brief sub nr
     * @return whether there are remaining tokens
     *
     */
    bool sub(ssize_t nr = 1);
    bool exhausted() const;
    size_t debug_actual_sub_nr() const;
    const TokenCore &core() const;
    TokenWrap clone(size_t batch_nr, size_t min_batch_size) const;

    ~TokenWrap()
    {
        CHECK(batch_remain_ <= 0 || core_exhausted_)
            << "** TokenWrap dctor with work undone.";
    }

private:
    TokenCore &core_;
    size_t batch_nr_{};
    ssize_t min_batch_size_{};

    int64_t task_per_sync_{};
    int64_t batch_remain_{0};
    int64_t guess_remain_{};
    bool core_exhausted_{false};

    size_t actual_sub_nr_{0};

    void update_per_sync()
    {
        task_per_sync_ = std::max((int64_t) (guess_remain_ / batch_nr_),
                                  (int64_t) min_batch_size_);
    }
};

/**
 * @brief StopTokenCore is the central class to signal other threads to exit
 * (like std::stop_token in c++ 20) and synchronize evaluation data.
 *
 * Usage:
 * Master thread owns StopTokenCore, while other threads own StopToken,
 * generated by stop_token_core.get_token();
 *
 */
class StopTokenCore;
class StopToken;

// StopToken lives within StopTokenCore
class StopToken
{
public:
    constexpr static auto lat_min = util::time::to_ns(0ns);
    constexpr static auto lat_max = util::time::to_ns(10ms);
    constexpr static auto lat_rng = util::time::to_ns(1us);

    using pointer = StopToken *;
    StopToken(StopTokenCore &core) : core_(core)
    {
    }
    /**
     * @brief sub nr
     * @return whether there are remaining tokens
     *
     */
    StopToken(const StopToken &) = delete;
    StopToken &operator=(StopToken &) = delete;
    StopToken(StopToken &&) = delete;
    StopToken &operator=(StopToken &&) = delete;

    bool complete_task(ssize_t nr = 1);
    bool stop_requested() const;
    void request_stop();
    const StopTokenCore &core() const;
    StopTokenCore &core();
    StopToken::pointer clone() const;
    int64_t nr() const
    {
        return complete_nr_.load(std::memory_order_relaxed);
    }
    int64_t global_nr() const;
    ~StopToken() = default;

    void collect_ns(uint64_t ns)
    {
        lat_m_.collect(ns);
    }

    const OnePassBucketMonitor<uint64_t> &latency_monitor() const
    {
        return lat_m_;
    }

private:
    StopTokenCore &core_;
    std::atomic<int64_t> complete_nr_{};
    std::atomic<bool> stop_requested_{};

    OnePassBucketMonitor<uint64_t> lat_m_{lat_min, lat_max, lat_rng};
};

class StopTokenCore
{
public:
    constexpr static auto lat_min = StopToken::lat_min;
    constexpr static auto lat_max = StopToken::lat_max;
    constexpr static auto lat_rng = StopToken::lat_rng;

    using pointer = std::unique_ptr<StopTokenCore>;
    StopTokenCore() = default;
    // does not allow copy nor move
    // because @TokenWrap owns a pointer to @this.
    StopTokenCore(const StopTokenCore &) = delete;
    StopTokenCore &operator=(StopTokenCore &) = delete;
    StopTokenCore(StopTokenCore &&) = delete;
    StopTokenCore &operator=(StopTokenCore &&) = delete;

    StopToken *get_token();

    bool stop_requested() const;
    void request_stop();

    uint64_t nr() const;
    ~StopTokenCore() = default;

    const OnePassBucketMonitor<uint64_t> &global_latency_monitor();

    friend class StopToken;

private:
    std::list<std::unique_ptr<StopToken>> proxy_;
    mutable std::mutex mu_;

    bool stop_requested_{false};

    OnePassBucketMonitor<uint64_t> lat_m_{lat_min, lat_max, lat_rng};
};

}  // namespace bench